sudo: required
services: 
  - docker

before_install: 
  - docker build -t  kartik0912/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kartik0912/react-test npm test -- --coverage

after_success:
  - docker build -t kartik0912/multi-client ./client
  - docker build -t kartik0912/multi-nginx ./nginx
  - docker build -t kartik0912/multi-server ./server

# login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# Take the built images and push them to Docker Hub
  - docker push kartik0912/multi-client
  - docker push kartik0912/multi-nginx
  - docker push kartik0912/multi-server